CREATE OR REPLACE FUNCTION TOTVSLG_USER(USERLG IN CHAR) RETURN CHAR 

AS 

CODIGO CHAR(17 BYTE);

BEGIN
    CODIGO := SUBSTR(USERLG, 11,1)||SUBSTR(USERLG, 15,1)||
              SUBSTR(USERLG, 2, 1)||SUBSTR(USERLG, 6, 1)||
              SUBSTR(USERLG, 10,1)||SUBSTR(USERLG, 14,1)||
              SUBSTR(USERLG, 1, 1)||SUBSTR(USERLG, 5, 1)||
              SUBSTR(USERLG, 9, 1)||SUBSTR(USERLG, 13,1)||
              SUBSTR(USERLG, 17,1)||SUBSTR(USERLG, 4, 1)||
              SUBSTR(USERLG, 8, 1);
  RETURN CODIGO;
END TOTVSLG_USER;
